# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d3700ab6af93bd993feff91b52be107d71438f741fbea761ef1111a9482975fecae74ef2e56887e155f73814cd956de8e0309a77b1abb7cdd493bc2c2070cec

test:
  secret_key_base: e536f4e0f2bd61e97e61010b8df562716c13740f11a86785d842c804117452dbbdb00c66ada02b4e5e8672f7ac70319f39be6185b39095c917604bed23cf38c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
